config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :customers, controllers: { confirmations: 'customer/confirmations' }
  devise_for :operators

  namespace :admin do
    root to: '/admin/dashboards#show'
    resource :dashboard, only: [:show]
    resources :transactions, only: [:index, :destroy]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :operators, only: [:index, :show, :edit, :update]
    resources :organizations do
      patch :geocode, on: :member
      resources :operator_organizations
      resources :transactions, only: [:index]
    end
  end

  namespace :customer do
    root to: 'dashboards#show'
    resource :dashboard, only: [:show]
    resources :organizations, only: [:index, :show]
  end

  namespace :operator do
    root to: 'transactions#index'
    # resource :dashboard, only: [:show]
    resources :transactions, only: [:index] do
      get :new_info, on: :collection
    end
    resources :customers, only: [] do
      resources :transactions, only: [:new, :create]
    end
  end

  # TODO: resources :organizations, only: [:index, :show]
  resources :sample_items

  get 'about' => 'pages#about', as: :about
  root 'pages#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/full_name.rb
require 'active_support/concern'

module FullName
  extend ActiveSupport::Concern

  def full_name
    if first_name.present? || last_name.present?
      "#{first_name} #{last_name}"
    else
      # fallback information
      email
    end
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  include FullName
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable,
         :lockable,
         :trackable,
         :omniauthable

  has_many :transactions

  def points_sum
    transactions.sum(:amount)
  end
end

app/models/operator.rb
class Operator < ApplicationRecord
  include FullName
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable,
         :lockable,
         :trackable

  has_many :transactions
  has_many :operator_organizations
  has_many :organizations, through: :operator_organizations
end

app/models/operator_organization.rb
class OperatorOrganization < ApplicationRecord
  belongs_to :operator
  belongs_to :organization
end

app/models/organization.rb
class Organization < ApplicationRecord
  extend Geocoder::Model::ActiveRecord
  validates :name, presence: true
  before_create :geocode
  geocoded_by :address
  has_many :transactions
  has_many :operator_organizations
  has_many :operators, through: :operator_organizations

  def address
    [street, city, country].compact.join(', ')
  end
end

app/models/sample_item.rb
class SampleItem < ApplicationRecord
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :customer
  belongs_to :operator
  belongs_to :organization
  belongs_to :transaction_category

  scope :created_by, -> (user) { where(created_by: user) }
  scope :for_realtime_admin_dashboard, -> { includes(:customer, :operator, :transaction_category).limit(100).order(created_at: :desc) }
end

app/models/transaction_category.rb
class TransactionCategory < ApplicationRecord
  has_many :transactions
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable,
         :lockable,
         :trackable,
         :omniauthable

  has_many :transactions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/sample_items_controller.rb
class SampleItemsController < ApplicationController
  before_action :set_sample_item, only: [:show, :edit, :update, :destroy]

  # GET /sample_items
  # GET /sample_items.json
  def index
    @sample_items = SampleItem.all
  end

  # GET /sample_items/1
  # GET /sample_items/1.json
  def show
  end

  # GET /sample_items/new
  def new
    @sample_item = SampleItem.new
  end

  # GET /sample_items/1/edit
  def edit
  end

  # POST /sample_items
  # POST /sample_items.json
  def create
    @sample_item = SampleItem.new(sample_item_params)

    respond_to do |format|
      if @sample_item.save
        format.html { redirect_to @sample_item, notice: 'Sample item was successfully created.' }
        format.json { render :show, status: :created, location: @sample_item }
      else
        format.html { render :new }
        format.json { render json: @sample_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sample_items/1
  # PATCH/PUT /sample_items/1.json
  def update
    respond_to do |format|
      if @sample_item.update(sample_item_params)
        format.html { redirect_to @sample_item, notice: 'Sample item was successfully updated.' }
        format.json { render :show, status: :ok, location: @sample_item }
      else
        format.html { render :edit }
        format.json { render json: @sample_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sample_items/1
  # DELETE /sample_items/1.json
  def destroy
    @sample_item.destroy
    respond_to do |format|
      format.html { redirect_to sample_items_url, notice: 'Sample item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sample_item
      @sample_item = SampleItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sample_item_params
      params.require(:sample_item).permit(:name, :enabled)
    end
end

app/helpers/admin/dashboards_helper.rb
module Admin::DashboardsHelper
end

app/helpers/admin/transactions_helper.rb
module Admin::TransactionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_account_switch
    render 'layouts/shared/account_switch' if account_switch_enabled?
  end

  def account_switch_enabled?
    count = [
      customer_signed_in?,
      operator_signed_in?,
      admin_signed_in?
    ].count(true)

    count > 1
  end
end

app/helpers/customer/dashboards_helper.rb
module Customer::DashboardsHelper
  def qr_code(customer)
    # URL for direct access into admin
    @url = url_for(new_operator_customer_transaction_url(customer.id))

    qrcode = RQRCode::QRCode.new(@url)

    svg = qrcode.as_svg(
      offset: 0,
      color: '000',
      shape_rendering: 'crispEdges',
      module_size: 10
    )

    "data:image/svg+xml;base64,#{Base64.encode64(svg)}"
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sample_items_helper.rb
module SampleItemsHelper
end

app/views/layouts/admin/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  .container
    = link_to admin_root_path, class: 'navbar-brand' do
      %i.fas.fa-unlock-alt.text-warning.mr-1
      Kávopič
    %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      %ul.navbar-nav.mr-auto
        %li.nav-item
          = link_to "Domov", admin_root_path, class: 'nav-link'
        %li.nav-item
          = link_to "Transakcie", admin_transactions_path, class: 'nav-link'
        %li.nav-item
          = link_to "Prevádzky", admin_organizations_path, class: 'nav-link'
        %li.nav-item
          = link_to "Operátori", admin_operators_path, class: 'nav-link'
        %li.nav-item
          = link_to "Zákazníci", admin_customers_path, class: 'nav-link'


      %ul.navbar-nav
        = render_account_switch

        - if admin_signed_in?
          %li.nav-item
            = link_to "Odhlásiť sa", destroy_admin_session_path, method: :delete, class: 'nav-link'
        - else
          %li.nav-item
            = link_to "Prihlásiť sa", new_admin_session_path, class: 'nav-link'

app/views/layouts/shared/_account_switch.html.haml
%li.nav-item.dropdown
  %a{class: 'nav-link dropdown-toggle', href: '#', id: "navbarDropdown", role: "button", 'data-toggle' => "dropdown", 'aria-haspopup' => "true", 'aria-expanded' => 'false'}
    Prepnúť sa
  .dropdown-menu{'aria-labelledby' => "navbarDropdown"}
    = link_to 'Zákazník', customer_root_path, class: 'dropdown-item' if customer_signed_in?
    = link_to 'Operátor', operator_root_path, class: 'dropdown-item' if operator_signed_in?
    = link_to 'Admin', admin_root_path, class: 'dropdown-item' if admin_signed_in?