config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :customers, controllers: { confirmations: 'customer/confirmations' }
  devise_for :operators

  namespace :admin do
    root to: '/admin/dashboards#show'
    resource :dashboard, only: [:show]
    resources :transactions, only: [:index, :destroy]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :operators, only: [:index, :show, :edit, :update]
    resources :organizations do
      patch :geocode, on: :member
      resources :operator_organizations
      resources :transactions, only: [:index]
    end
  end

  namespace :customer do
    root to: 'dashboards#show'
    resource :dashboard, only: [:show]
    resources :organizations, only: [:index, :show]
  end

  namespace :operator do
    root to: 'transactions#index'
    # resource :dashboard, only: [:show]
    resources :transactions, only: [:index] do
      get :new_info, on: :collection
    end
    resources :customers, only: [] do
      resources :transactions, only: [:new, :create]
    end
  end

  # TODO: resources :organizations, only: [:index, :show]
  resources :sample_items

  get 'about' => 'pages#about', as: :about
  root 'pages#index'
end

app/models/customer.rb
class Customer < ApplicationRecord
  include FullName
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable,
         :lockable,
         :trackable,
         :omniauthable

  has_many :transactions

  def points_sum
    transactions.sum(:amount)
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  before_action :find_customer, only: [:show, :edit, :update]
  layout 'admin'

  def index
    @customers = Customer.order(created_at: :desc)
  end

  def show
  end

  def edit
  end

  def update
    if @customer.update customer_params
      redirect_to admin_customer_url(@customer), notice: 'Zákazník bol uložený.'
    else
      render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:first_name, :last_name)
  end

  def find_customer
    @customer = Customer.find params[:id]
  end
end

app/controllers/customer/confirmations_controller.rb
class Customer::ConfirmationsController < Devise::ConfirmationsController
  def show
    super do |resource|
      sign_in(resource)
    end
  end
end

app/controllers/customer/dashboards_controller.rb
class Customer::DashboardsController < ApplicationController
  before_action :authenticate_customer!
  layout 'customer'

  def show
  end
end

app/controllers/customer/organizations_controller.rb
class Customer::OrganizationsController < ApplicationController
  before_action :authenticate_customer!
  layout 'customer'

  def index
    @organizations = Organization.geocoded.order(created_at: :desc)
    @geographic_center = Geocoder::Calculations.geographic_center(@organizations)
  end

  def show
    @organization = Organization.find params[:id]
  end
end

app/helpers/customer/dashboards_helper.rb
module Customer::DashboardsHelper
  def qr_code(customer)
    # URL for direct access into admin
    @url = url_for(new_operator_customer_transaction_url(customer.id))

    qrcode = RQRCode::QRCode.new(@url)

    svg = qrcode.as_svg(
      offset: 0,
      color: '000',
      shape_rendering: 'crispEdges',
      module_size: 10
    )

    "data:image/svg+xml;base64,#{Base64.encode64(svg)}"
  end
end

app/helpers/customer/organizations_helper.rb
module Customer::OrganizationsHelper
end

app/views/layouts/customer/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-primary
  .container
    = link_to 'Kávopič', customer_root_path, class: 'navbar-brand'
    %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      %ul.navbar-nav.mr-auto
        %li.nav-item
          = link_to 'Domov', customer_root_path, class: 'nav-link'
        %li.nav-item
          = link_to 'Mapa', customer_organizations_path, class: 'nav-link'

      %ul.navbar-nav
        = render_account_switch

        - if customer_signed_in?
          %li.nav-item
            = link_to "Odhlásiť sa", destroy_customer_session_path, method: :delete, class: 'nav-link'
        - else
          %li.nav-item
            = link_to "Prihlásiť sa", new_customer_session_path, class: 'nav-link'