config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :customers, controllers: { confirmations: 'customer/confirmations' }
  devise_for :operators

  namespace :admin do
    root to: '/admin/dashboards#show'
    resource :dashboard, only: [:show]
    resources :transactions, only: [:index, :destroy]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :operators, only: [:index, :show, :edit, :update]
    resources :organizations do
      patch :geocode, on: :member
      resources :operator_organizations
      resources :transactions, only: [:index]
    end
  end

  namespace :customer do
    root to: 'dashboards#show'
    resource :dashboard, only: [:show]
    resources :organizations, only: [:index, :show]
  end

  namespace :operator do
    root to: 'transactions#index'
    # resource :dashboard, only: [:show]
    resources :transactions, only: [:index] do
      get :new_info, on: :collection
    end
    resources :customers, only: [] do
      resources :transactions, only: [:new, :create]
    end
  end

  # TODO: resources :organizations, only: [:index, :show]
  resources :sample_items

  get 'about' => 'pages#about', as: :about
  root 'pages#index'
end

app/models/customer.rb
class Customer < ApplicationRecord
  include FullName
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable,
         :lockable,
         :trackable,
         :omniauthable

  has_many :transactions

  def points_sum
    transactions.sum(:amount)
  end
end

app/models/organization.rb
class Organization < ApplicationRecord
  extend Geocoder::Model::ActiveRecord
  validates :name, presence: true
  before_create :geocode
  geocoded_by :address
  has_many :transactions
  has_many :operator_organizations
  has_many :operators, through: :operator_organizations

  def address
    [street, city, country].compact.join(', ')
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  before_action :find_customer, only: [:show, :edit, :update]
  layout 'admin'

  def index
    @customers = Customer.order(created_at: :desc)
  end

  def show
  end

  def edit
  end

  def update
    if @customer.update customer_params
      redirect_to admin_customer_url(@customer), notice: 'Zákazník bol uložený.'
    else
      render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:first_name, :last_name)
  end

  def find_customer
    @customer = Customer.find params[:id]
  end
end

app/controllers/admin/organizations_controller.rb
class Admin::OrganizationsController < ApplicationController
  before_action :authenticate_admin!
  before_action :find_organization, only: [:show, :edit, :update, :destroy, :geocode]
  layout 'admin'

  def index
    @organizations = Organization.includes(:transactions).order(created_at: :desc)
  end

  def show
  end

  def new
    @organization = Organization.new
  end

  def create
    @organization = Organization.new organization_params
    if @organization.save
      redirect_to [:admin, @organization], notice: 'Prevádzka bola pridaná'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @organization.update organization_params
      redirect_to [:admin, @organization], notice: 'Prevádzka bola aktualizovaná.'
    else
      render :edit
    end
  end

  def destroy
    @organization.destroy
    redirect_to admin_organizations_url, notice: 'Prevádzka bola odstránená.'
  end

  def geocode
    @organization.geocode
    @organization.save!
    redirect_to [:admin, @organization]
  end

  private

  def find_organization
    @organization = Organization.find params[:id]
  end

  def organization_params
    params.require(:organization).permit(
      :name,
      :street,
      :city,
      :country,
      :latitude,
      :longitude,
    )
  end
end

app/controllers/customer/confirmations_controller.rb
class Customer::ConfirmationsController < Devise::ConfirmationsController
  def show
    super do |resource|
      sign_in(resource)
    end
  end
end

app/controllers/customer/dashboards_controller.rb
class Customer::DashboardsController < ApplicationController
  before_action :authenticate_customer!
  layout 'customer'

  def show
  end
end

app/controllers/customer/organizations_controller.rb
class Customer::OrganizationsController < ApplicationController
  before_action :authenticate_customer!
  layout 'customer'

  def index
    @organizations = Organization.geocoded.order(created_at: :desc)
    @geographic_center = Geocoder::Calculations.geographic_center(@organizations)
  end

  def show
    @organization = Organization.find params[:id]
  end
end

app/helpers/customer/dashboards_helper.rb
module Customer::DashboardsHelper
  def qr_code(customer)
    # URL for direct access into admin
    @url = url_for(new_operator_customer_transaction_url(customer.id))

    qrcode = RQRCode::QRCode.new(@url)

    svg = qrcode.as_svg(
      offset: 0,
      color: '000',
      shape_rendering: 'crispEdges',
      module_size: 10
    )

    "data:image/svg+xml;base64,#{Base64.encode64(svg)}"
  end
end

app/helpers/customer/organizations_helper.rb
module Customer::OrganizationsHelper
end

app/views/customer/organizations/index.html.haml
%h2 Mapa
#organizations_map

app/views/customer/organizations/index.js.erb
var map = L.map('organizations_map', {
  center: <%= @geographic_center %>,
  zoom: 15
});

var myIcon = L.icon({
    iconUrl: '/map_icons/coffee_icon.png',
    iconSize: [32, 32],
});

// L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
// 	attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
// 	maxZoom: 18,
// 	id: 'mapbox.streets',
// 	accessToken: 'pk.eyJ1Ijoia2F2b3BpYyIsImEiOiJjazFjMGc1ZTAxcmVrM2xtcmN3ZjdiZndyIn0.3NEklL5iBzDehSrD1BFrwg'
// }).addTo(map);

L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
  attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>',
  maxZoom: 18
}).addTo(map)

<% @organizations.each do |organization| %>
  var marker = L.marker([<%= organization.latitude %>, <%= organization.longitude %>], {icon: myIcon}).addTo(map);
  // marker.bindPopup("<b><%= organization.name %></b><br>1 bod za kávu")//.openPopup()
  marker.on('click', function() {
    Turbolinks.visit('<%= customer_organization_url(organization) %>')
  });
<% end %>

// const onMapClick = function(e) {
//   const popup = L.popup();
//   popup.setLatLng(e.latlng);
//   popup.setContent(`You clicked the map at ${e.latlng}`);
//   popup.openOn(map);
//   return console.log(`Coordinate: ${e.latlng}`);
// };
//
// map.on('click', onMapClick);

app/views/customer/organizations/show.html.haml
%h2 Detail prevádzky

.row
  .col-sm
    %p
      Názov: <br>
      #{@organization.name}
    %p
      Adresa: <br>
      #{@organization.address}
    %p
      Súradnice: <br>
      #{@organization.to_coordinates}
    %p
      Dátum vytvorenia:<br>
      #{l @organization.created_at, format: :long}
    %p
      = link_to 'Späť na mapu',
        customer_organizations_path,
        class: 'btn btn-primary btn-sm'
  .col-sm
    #admin_organization_map

:javascript

  var map = L.map('admin_organization_map', {
    center: [#{@organization.latitude}, #{@organization.longitude}],
    zoom: 16
  });

  var myIcon = L.icon({
      iconUrl: '/map_icons/coffee_icon.png',
      iconSize: [32, 32],
  });

  L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
    attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>',
    maxZoom: 18
  }).addTo(map)


  var marker = L.marker([#{@organization.latitude}, #{@organization.longitude}], {icon: myIcon}).addTo(map);